### ISSUE TITLE
The method driver /usr/lib/apt/methods/https could not be found

### ISSUE THREAD

**Issue by ThomasTr** [bassmaster187/TeslaLogger#695] opened 2021-11-24 18:29 UTC
As this issue (https://github.com/bassmaster187/TeslaLogger/issues/692)  was closed by owner, but still unresolved, I'll open a new one.

Got same error message while building docker images:

````
E: The method driver /usr/lib/apt/methods/https could not be found.
The command '/bin/sh -c apt-get update &&   apt-get install -y --no-install-recommends git &&   apt-get install -y --no-install-recommends mariadb-client &&   apt-get clean &&   apt-get autoremove -y &&   rm -rf /var/lib/apt/lists/* &&   echo "export TERM=xterm" >> /root/.bashrc  &&   echo "DOCKER" >> /tmp/teslalogger-DOCKER' returned a non-zero code: 100
````

The change in Dockerfile `docker/teslalogger/Dockerfile` suggested in this issue fixed the issue for me:
````
# install packages
RUN ln -s /usr/lib/apt/methods/http /usr/lib/apt/methods/https && \
  rm /etc/apt/sources.list.d/mono-official-stable.list && \
  apt-get update && \
  apt-get install -y --no-install-recommends apt-transport-https && \
  apt-get install -y --no-install-recommends git && \
  apt-get install -y --no-install-recommends mariadb-client && \
  apt-get clean && \
  apt-get autoremove -y && \
  rm -rf /var/lib/apt/lists/* && \
  echo "export TERM=xterm" >> /root/.bashrc  && \
  echo "DOCKER" >> /tmp/teslalogger-DOCKER
````

Can provide pull request if you are interested in fixing this. Could prevent more issue reports.

**Comment by bassmaster187** [comment] 2021-11-24 19:51
do you know if this has some sideeffects to old users?

**Comment by Obihoernchen** [comment] 2021-11-25 00:34
This is also fixed in newest mono container: https://github.com/mono/docker/issues/89
And all you need is `rm /etc/apt/sources.list.d/mono-official-stable.list` as the mono repo is not used afterwards.

**Comment by ThomasTr** [comment] 2021-11-25 10:29
As @Obihoernchen mentioned, it is enough to add `rm /etc/apt/sources.list.d/mono-official-stable.list`, as for this list https transport is required which is not installed.

@Obihoernchen linked his issue #694:
While switching from mono:5.20.1.34 to mono you are also switching the mono version to actually 6.12.0.122. I don't know if this is @bassmaster187 will.

Also i get the following warning:
W: Conflicting distribution: https://download.mono-project.com/repo/debian stable-buster/snapshots/6.12.0.122 InRelease (expected stable-buster/snapshots/6.12.0.122 but got buster)

I think, there are now side effects for older users. The bigger effect is, that the build process is actually broken and should be fixed.

**Comment by bassmaster187** [comment] 2021-12-08 20:28
Mono 6.12.0.122 must be tested, but as far as I know Version 6 got some memory leaks

**Comment by bassmaster187** [comment] 2022-02-14 11:44
Please try again with new docker file.

**Comment by a-xin** [comment] 2022-04-02 18:58
This seems to be fixed for me. I was running into this issue in January but can't reproduce it anymore with the latest version (1.52.3.0)

**Closed** 2024-11-04 09:28 UTC
Labels: bug
