### ISSUE TITLE
Charging cost issue

### ISSUE THREAD

**Issue by Tobor7** [bassmaster187/TeslaLogger#1012] opened 2023-05-08 17:20 UTC
I found a bug with the latest Teslalogger update (1.54.20.0). If a manual cost was entered on a previous charging session, the cost per charge is also copied on the charge per minute field.

![image](https://user-images.githubusercontent.com/90622675/236887690-17ba19eb-4f18-416d-ace4-7bafe5f2f367.png)

![image](https://user-images.githubusercontent.com/90622675/236888117-11f2f56a-6694-44a6-b224-538f8d6cf88d.png)

**Comment by superfloh247** [comment] 2023-05-08 17:22
this has been reported by some people, but I haven't found a way to reproduce it.
please attach your complete /etc/teslalogger/nohup.out and all /etc/teslalogger/backup/logfile*.gz to this issue

**Comment by superfloh247** [comment] 2023-05-08 21:29
found and reproduced

I fucked up big time

**Comment by Adminius** [comment] 2023-05-30 11:36
https://github.com/bassmaster187/TeslaLogger/blob/master/docs/en/faq.md#grafana-dashboard-charging-history--ladehistorie-has-wrong-entries-for-total-costs

**Comment by superfloh247** [comment] 2023-05-30 12:49
looks like docker, so you need the port of the TeslaLogger process, not the admin Webserver --> please try :5010

**Comment by Tobor7** [comment] 2023-05-30 17:13
Thanks superfloh247, it is working with port 5010.
(May I suggest to change the FAQ example to use the port 5010 instead of 5000 and specify to use the port of Teslalogger and not the webserver.)

Unfortunately, I am unable to pass the step one, I am in the "TeslaLogger is processing your file" state for over 2 hours, for a archive file that is only 6 MB. (This is my second attempt, I stop the first after 1h)

**Comment by superfloh247** [comment] 2023-05-30 17:58
Ah yes

the FAQ is already updated, or at least I raised a PR

and the other thing, take a look at your log file, I guess it contains something like

System.IO.FileNotFoundException: Could not load file or assembly ‚HttpMultipartParser, Version=8.1.0.0, Culture=neutral, PublicKeyToken=6d293681fa6c7a03‘ or one of its dependencies.

somebody forgot to add the new DLLs required by my code to the new release ...

**Comment by Tobor7** [comment] 2023-05-30 19:44
I have the following error:
30.05.2023 15:41:51 : WebServer Exception Localpath: /RestoreChargingCostsFromBackup2
System.IO.FileNotFoundException: Could not load file or assembly 'HttpMultipartParser, Version=8.1.0.0, Culture=neutral, PublicKeyToken=6d293681fa6c7a03' or one of its dependencies.

So I guess I don't have the required DLL. Is there a way to install it manually or should I wait for the next release?

**Comment by superfloh247** [comment] 2023-05-30 20:28
just wait :)

**Comment by Adminius** [comment] 2023-11-09 17:32
@Tobor7 can you please close the issue?

**Closed** 2023-11-09 18:10 UTC
Labels: bug
